version: 1.0.{build}

branches:
  except:
    - gh-pages

skip_tags: true

install:
  - .paket\paket.bootstrapper.exe
  - .paket\paket.exe restore

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

cache:
  - packages -> paket.lock

build:
  parallel: true
  project: AzureRmRest.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  
artifacts:
  - path: src\bin\$(configuration)\AzureRmRest.dll
  - path: src\bin\$(configuration)\AzureRmRest.pdb

deploy:
  - provider: GitHub
    release: AzureRmRest-v$(appveyor_build_version)
    auth_token:
      secure: AKvncEaWXvKGoLiiYaxf3NvS+ZIlExjXhc9hugLtkig2sot+nSYrxN15M8IjkN3A
    artifact: /.*\.(dll|pdb|nupkg)/
    draft: false
    prerelease: false
    on:
      branch: master

  - provider: NuGet
    api_key:
      secure: PdQVmQyPYXHarPzHJRWrtbhGvOXgAL1cp5xNfg0K9MQ6YIXyr3Jpjk/6nOsmX6XN
    skip_symbols: false
    artifact: /.*\.nupkg/
