version: 1.0.{build}

branches:
  except:
    - gh-pages

skip_tags: true

install:
  - .paket\paket.bootstrapper.exe
  - .paket\paket.exe restore

configuration: Release

build:
  parallel: true
  project: Fake.AzureRm.sln
  
artifacts:
  - path: bin\Release\*.dll
  - path: bin\Release\*.pdb
