version: 1.0.{build}

branches:
  except:
    - gh-pages

skip_tags: true

install:
  - .paket\paket.bootstrapper.exe
  - .paket\paket.exe restore

configuration: Release

cache:
  - packages -> paket.lock

build:
  parallel: true
  project: Fake.AzureRm.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  
artifacts:
  - path: src\bin\$(configuration)\Fake.AzureRm.dll
  - path: src\bin\$(configuration)\Fake.AzureRm.pdb

deploy:
  - provider: GitHub
    release: Fake.AzureRm-v$(appveyor_build_version)
    auth_token:
      secure: AKvncEaWXvKGoLiiYaxf3NvS+ZIlExjXhc9hugLtkig2sot+nSYrxN15M8IjkN3A
    artifact: /.*\.(dll|pdb|nupkg)/
    draft: false
    prerelease: false
    on:
      branch: master

  - provider: NuGet
    api_key:
      secure: 3lx2hPglCgr4j9T+TbHIsHTNwwwxq7WsDk7poMu6KjwLS3pUHNW3HWC6xtikKMI/
    skip_symbols: false
    artifact: /.*\.nupkg/