version: 1.0.{build}

branches:
  except:
    - gh-pages

skip_tags: true

install:
  - dotnet install

configuration: Release

build:
  parallel: true
  project: AzureRmRest.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  
artifacts:
  - path: src\bin\$(configuration)\AzureRmRest.dll
  - path: src\bin\$(configuration)\AzureRmRest.pdb