version: 1.0.{build}

branches:
  except:
    - gh-pages

skip_tags: true

install:
  - .paket\paket.bootstrapper.exe
  - .paket\paket.exe restore

configuration: Release

cache:
  - packages -> paket.lock

build:
  parallel: true
  project: Fake.AzureRm.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  
artifacts:
  - path: bin\$(configuration)\Fake.AzureRm.dll
  - path: bin\$(configuration)\Fake.AzureRm.pdb

deploy:
  release: Fake.AzureRm-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: AKvncEaWXvKGoLiiYaxf3NvS+ZIlExjXhc9hugLtkig2sot+nSYrxN15M8IjkN3A
  artifact: /.*\.(dll|pdb)/
  draft: false
  prerelease: false
  on:
    branch: master
