version: 1.0.{build}

branches:
  except:
    - gh-pages

skip_tags: true

install:
  - .paket\paket.bootstrapper.exe
  - .paket\paket.exe restore

configuration: Release

build:
  parallel: true
  project: Fake.AzureRm.sln
  
artifacts:
  - path: bin\Release\Fake.AzureRm.*

deploy:
  release: Fake.AzureRm-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: AKvncEaWXvKGoLiiYaxf3NvS+ZIlExjXhc9hugLtkig2sot+nSYrxN15M8IjkN3A
  artifact: /.*\.(dll|pdb|xml)/
  draft: false
  prerelease: false
  on:
    branch: master
